use crate::ip_network::IpNetwork;
use serde::{Deserialize, Serialize};
use std::net::IpAddr;

/// Compact application-layer method identifier. Kept numeric on the hot path.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum HttpMethod {
    #[default]
    Other = 0,
    Get = 1,
    Post = 2,
    Put = 3,
    Patch = 4,
    Delete = 5,
    Head = 6,
    Options = 7,
    Connect = 8,
    Trace = 9,
}

#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
#[repr(u8)]
pub enum HttpVersion {
    #[default]
    Other = 0,
    Http1 = 1,
    Http2 = 2,
    Http3 = 3,
}

/// Bounded HTTP/2 stream telemetry supplied by a terminating proxy.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct Http2Telemetry {
    pub active_streams: u32,
    pub streams_opened: u32,
    pub streams_reset: u32,
    pub streams_completed: u32,
}

/// L7 metadata is deliberately bounded: RamShield reasons over normalized
/// identities, not arbitrary URLs, headers or bodies. Hashes are stable values
/// generated by the telemetry producer.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct L7Metadata {
    #[serde(default)]
    pub host_hash: u64,
    #[serde(default)]
    pub route_hash: u64,
    #[serde(default)]
    pub method: HttpMethod,
    #[serde(default)]
    pub version: HttpVersion,
    #[serde(default)]
    pub latency_us: u64,
    #[serde(default)]
    pub request_bytes: u32,
    #[serde(default)]
    pub response_bytes: u64,
    #[serde(default)]
    pub http2: Option<Http2Telemetry>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectionEvent {
    pub ip: IpAddr,
    pub timestamp_ns: u64,
    pub bytes: u64,
    pub status_code: u16,
    pub proto_fingerprint: u32,
    /// Optional application-layer telemetry. `None` preserves the legacy L3/L4
    /// contract and keeps existing producers wire-compatible.
    #[serde(default)]
    pub l7: Option<L7Metadata>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct BlockDecision {
    pub ip: IpAddr,
    pub reason: crate::error::BlockReason,
    pub ttl_secs: Option<u64>,
    /// Batch subnet that triggered the block (IPv4 /24 or IPv6 /64).
    pub batch_subnet: Option<IpNetwork>,
}
